### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by getorca** [cloudflare/worker-emscripten-template#10]
I'm sporadically getting the following error:
```
Uncaught (in promise)
RuntimeError: memory access out of bounds
    at _malloc (<anonymous>:wasm-function[68]:0x1fbd6)
    at _init (<anonymous>:wasm-function[15]:0x3408)
    at Object.e._init [as init] (worker.js:1:7350)
    at worker.js:1:11030
Uncaught (in response)
Error: internal error

```

**Comment by EverlastingBugstopper** [comment]
Is this with the base template + no other changes or are you using your own modified code?

**Comment by getorca** [comment]
yes, base template no changes

**Comment by EverlastingBugstopper** [comment]
Can you give me some info on your environment? Version of node, version of Wrangler, operating system - anything else you find pertinent. I can't seem to reproduce this
